# Generated by Django 5.1.4 on 2025-01-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product/detail/image', verbose_name='Картинка для товара'),
        ),
    ]
