# Generated by Django 5.1.4 on 2025-01-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_product_images_productgallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image_product',
            new_name='image',
        ),
    ]
