# Generated by Django 5.1.4 on 2025-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_review_text_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_in_cart',
            field=models.BooleanField(default=False, verbose_name='стасус'),
        ),
    ]
