# Generated by Django 5.1.4 on 2025-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cartitem_is_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_in_cart',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
